import string
from collections import defaultdict


cipherText = (
"QEJFTHVBJQLTKDJWCKUSJHAIAGOZZTEOLJDJWGOZZTQEOBNEIETATFTAGOSATQQEJQIZJGOZZTIWJZJZFJW"
"GOZZTTHAGOBSAOHSCKTCQETNCOBDJWCFBGEAOQIHOLWJUJTQIQZOWJGOWWJGQSCQETHRCOBDJWCZBGEXOWG"
"OZIHNQOZCSIQQSJUTWQCAOQOFKQIHTQJKISJHGJAOQQEJCTSSXJTWJAQETQTKOHNOWKOZJUOJQWCLTKHOLI"
"ZZIHJHQTHAQEJCLJWJNJQQIHNFOWJAAOQLECGOBSAHQEJKQOUQTSRIHNTHASJQQEJZAWIHREIKEJTSQEFBQ"
"FISFOAIAHOQKIHNOWWJGIQJAOQEJUTBKJAXOWTZOZJHQAOQQEIWASCTHAXIHTSSCGOZZTEJKTIAGOZZTILI" 
"KEQOZTRJTHTHHOBHGJZJHQ")

ngrams = defaultdict(int)
n = 3

for j in range((len(cipherText) - n)):
	ngrams[cipherText[j:j+n]] += 1

for x in sorted(ngrams, key=ngrams.get, reverse=False):
	print(x + ':' + str(ngrams[x]))

