import string

cipherText = "QEJFTHVBJQLTKDJWCKUSJHAIAGOZZTEOLJDJWGOZZTQEOBNEIETATFTAGOSATQQEJQIZJGOZZTIWJZJZFJWGOZZTTHAGOBSAOHSCKTCQETNCOBDJWCFBGEAOQIHOLWJUJTQIQZOWJGOWWJGQSCQETHRCOBDJWCZBGEXOWGOZIHNQOZCSIQQSJUTWQCAOQOFKQIHTQJKISJHGJAOQQEJCTSSXJTWJAQETQTKOHNOWKOZJUOJQWCLTKHOLIZZIHJHQTHAQEJCLJWJNJQQIHNFOWJAAOQLECGOBSAHQEJKQOUQTSRIHNTHASJQQEJZAWIHREIKEJTSQEFBQFISFOAIAHOQKIHNOWWJGIQJAOQEJUTBKJAXOWTZOZJHQAOQQEIWASCTHAXIHTSSCGOZZTEJKTIAGOZZTILIKEQOZTRJTHTHHOBHGJZJHQGO"
plainText = ''

decryptMapping = {
	'A' : 'R',
	'B' : 'W',
	'C' : 'U',
	'D' : 'K',
	'E' : 'H',
	'F' : 'P',
	'G' : 'C',
	'H' : 'I',
	'I' : 'S',
	'J' : 'E',
	'K' : 'J',
	'L' : 'Y',
	'M' : 'Z',
	'N' : 'G',
	'O' : 'O',
	'P' : 'Q',
	'Q' : 'T',
	'R' : 'V',
	'S' : 'L',
	'T' : 'A',
	'U' : 'F',
	'V' : 'N',
	'W' : 'D',
	'X' : 'B',
	'Y' : 'X',
	'Z' : 'M'
}


for i in range(len(cipherText)):
	plainText += decryptMapping[cipherText[i]]

print()
print(cipherText)
print()
print(plainText)